name: checkout-test

on:
  workflow_dispatch:

jobs:
  # デプロイJOB
  codecommit:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      # 2. 別のPrivateリポジトリからソースコードをチェックアウト
      - name: 2. Github Repository Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          # プライベートリポジトリを指定
          repository: junichi-nishimura-flect/test-cicd-private
          # checkout 先のパスを指定
          path: ./test-cicd-private
          ref: develop

      # 3. ブランチの確認
      - name: 3. Push Other Repository
        run: |
            git branch -a
            git status -sb