name: tag-test

on:
  push:
    tags:
      # v9.9.9-keycloak / dev-release-keycloak-yyyy-mm-dd-99
      - "v[0-9]+.[0-9]+.[0-9]+-keycloak"
      - "dev-release-keycloak-20[0-9][0-9]-[01][0-9]-[03][0-9]-[0-9]+"
  workflow_dispatch:

jobs:
  # デプロイJOB
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 環境を確認
      - name: 1. Check Environment
        run: |
          echo '1' $GITHUB_REF#refs/tags/
          echo '2' ${{ github.ref }}
        # echo 'tag' => ${GITHUB_REF#refs/tags/}
        # echo github_ref : ${{ github.ref }}
        # echo 'ref_name :' '${{ github.ref_name }}'
          # echo 'event_repository_name :' ${{ github.event.repository.name }}
          # echo 'sha :' ${{ github.sha }}
          # echo head_ref ${{ github.head_ref }}
          # echo base_ref ${{ github.base_ref }}
          # echo 成功しました

