name: test-cicd

on:
  # 手動実行できるようにする
  workflow_dispatch:

jobs:
  # デプロイJOB
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ (github.ref == 'refs/heads/develop' && 'develop') || (github.ref == 'refs/heads/staging' && 'staging') || (github.ref == 'refs/heads/main' && 'production') || '' }}
    steps:      
      - name: check
        run: |      
          echo ${{ vars.CDK_BRANCH_BATCH }}
          echo ${{ vars.CDK_BRANCH_CDK }}
          echo ${{ vars.CDK_STACK_NAME }}     
          echo ${{ github.event.repository.name }}
          echo ${{ github.sha }}
          exit 1
      
      - name : Notification on Success
        if: ${{ success() }}
        run: |      
          echo 成功しました

      - name : Notification on Success
        if: ${{ failure() }}
        run: |      
          echo 失敗しました
